import * as pdfjsLib from 'pdfjs-dist';
import mammoth from 'mammoth';

// Set up pdfjs worker using cdnjs for browser runtime compatibility
pdfjsLib.GlobalWorkerOptions.workerSrc = `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjsLib.version}/pdf.worker.min.js`;

/**
 * Parses uploaded PDF, DOCX, TXT, or JSON file and extracts readable plain text or embedded JSON metadata.
 * Returns { isJson: boolean, text?: string, data?: object }
 */
export async function extractTextFromFile(file) {
  if (!file) throw new Error('No file selected.');

  const fileName = file.name.toLowerCase();

  // JSON Backup Files
  if (fileName.endsWith('.json')) {
    const content = await file.text();
    try {
      return { isJson: true, data: JSON.parse(content) };
    } catch (e) {
      throw new Error('Invalid JSON backup file format.');
    }
  }

  // TXT Files
  if (fileName.endsWith('.txt')) {
    const content = await file.text();
    if (content.trim().startsWith('{') && content.trim().endsWith('}')) {
      try {
        return { isJson: true, data: JSON.parse(content) };
      } catch (e) {}
    }
    return { isJson: false, text: content };
  }

  // DOCX Files
  if (fileName.endsWith('.docx')) {
    const arrayBuffer = await file.arrayBuffer();
    const result = await mammoth.extractRawText({ arrayBuffer });
    const text = result.value || '';
    if (!text.trim()) {
      throw new Error('This DOCX document appears to be empty or unreadable.');
    }
    return { isJson: false, text };
  }

  // PDF Files
  if (fileName.endsWith('.pdf')) {
    const arrayBuffer = await file.arrayBuffer();
    const loadingTask = pdfjsLib.getDocument({ data: arrayBuffer });
    const pdf = await loadingTask.promise;
    
    // 1. Check embedded PDF metadata (Subject/Keywords) for resumes generated by our Resume Builder
    try {
      const metadata = await pdf.getMetadata();
      const subject = metadata?.info?.Subject || metadata?.info?.subject;
      if (subject && (subject.startsWith('{') || subject.includes('fullName'))) {
        const parsedJson = JSON.parse(subject);
        if (parsedJson && typeof parsedJson === 'object') {
          return { isJson: true, data: parsedJson };
        }
      }
    } catch (e) {
      console.warn('Metadata check skipped:', e);
    }

    // 2. Extract text items from PDF pages
    let fullText = '';
    for (let pageNum = 1; pageNum <= pdf.numPages; pageNum++) {
      const page = await pdf.getPage(pageNum);
      const textContent = await page.getTextContent();
      const pageText = textContent.items.map(item => item.str).join(' ');
      fullText += pageText + '\n';
    }

    if (!fullText.trim()) {
      // Check if browser has localStorage saved data to suggest restoring
      const hasSavedLocalStorage = !!localStorage.getItem('built_resume_data');
      if (hasSavedLocalStorage) {
        throw new Error('This PDF file was created prior to text embedding. Click "⚡ Restore Last Created Resume" below to load your saved resume instantly!');
      } else {
        throw new Error('This PDF file contains scanned image data without readable text. Please upload a text-based PDF, DOCX, TXT, or JSON backup file.');
      }
    }

    return { isJson: false, text: fullText };
  }

  throw new Error('Unsupported file format. Please upload a PDF, DOCX, TXT, or JSON file.');
}

/**
 * Extracts guaranteed plain text string from PDF, DOCX, TXT, or JSON file.
 * Safely converts structured JSON resume data into formatted text string if needed.
 */
export async function extractPlainTextFromFile(file) {
  const result = await extractTextFromFile(file);

  if (result.isJson && result.data) {
    const d = result.data;
    const lines = [
      d.fullName ? d.fullName.toUpperCase() : '',
      [d.email, d.phone, d.location, d.linkedin, d.github].filter(Boolean).join(' | '),
      d.jobTitle ? `TARGET ROLE: ${d.jobTitle}` : '',
      d.summary ? `\nSUMMARY:\n${d.summary}` : '',
      (d.otherSkills || d.skills) ? `\nTECHNICAL SKILLS:\n${d.otherSkills || d.skills}` : '',
      d.experiences?.length > 0 ? `\nWORK EXPERIENCE:\n` + d.experiences.map(e => `${e.jobTitle || ''} at ${e.company || ''} (${e.startDate || ''} - ${e.endDate || ''})\n${e.responsibilities || ''}`).join('\n') : '',
      d.projects?.length > 0 ? `\nKEY PROJECTS:\n` + d.projects.map(p => `${p.title || ''} ${p.techStack ? `(${p.techStack})` : ''}\n${p.description || ''}`).join('\n') : '',
      d.certifications?.length > 0 ? `\nCERTIFICATIONS:\n` + d.certifications.map(c => `${c.name || ''} - ${c.issuer || ''} ${c.year || ''}`).join('\n') : '',
      d.educations?.length > 0 ? `\nEDUCATION:\n` + d.educations.map(ed => `${ed.degree || ''} ${ed.fieldOfStudy ? `in ${ed.fieldOfStudy}` : ''} ${ed.score ? `(${ed.score})` : ''} - ${ed.university || ''} (${ed.gradYear || ''})`).join('\n') : ''
    ].filter(Boolean);

    return lines.join('\n');
  }

  return result.text || '';
}
