import * as pdfjsLib from 'pdfjs-dist';
import mammoth from 'mammoth';

// Set up pdfjs worker using cdnjs for browser runtime compatibility
pdfjsLib.GlobalWorkerOptions.workerSrc = `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjsLib.version}/pdf.worker.min.js`;

/**
 * Parses uploaded PDF, DOCX, or TXT file and extracts readable plain text or embedded JSON metadata.
 * Returns { isJson: boolean, text?: string, data?: object }
 */
export async function extractTextFromFile(file) {
  if (!file) throw new Error('No file selected.');

  const fileName = file.name.toLowerCase();

  // TXT Files
  if (fileName.endsWith('.txt')) {
    const content = await file.text();
    // Check if it's a JSON file saved as txt
    if (content.trim().startsWith('{') && content.trim().endsWith('}')) {
      try {
        return { isJson: true, data: JSON.parse(content) };
      } catch (e) {}
    }
    return { isJson: false, text: content };
  }

  // DOCX Files
  if (fileName.endsWith('.docx')) {
    const arrayBuffer = await file.arrayBuffer();
    const result = await mammoth.extractRawText({ arrayBuffer });
    const text = result.value || '';
    if (!text.trim()) {
      throw new Error('This DOCX document appears to be empty or unreadable.');
    }
    return { isJson: false, text };
  }

  // PDF Files
  if (fileName.endsWith('.pdf')) {
    const arrayBuffer = await file.arrayBuffer();
    const loadingTask = pdfjsLib.getDocument({ data: arrayBuffer });
    const pdf = await loadingTask.promise;
    
    // 1. Check embedded PDF metadata (Subject/Keywords) for resumes generated by our Resume Builder
    try {
      const metadata = await pdf.getMetadata();
      const subject = metadata?.info?.Subject || metadata?.info?.subject;
      if (subject && (subject.startsWith('{') || subject.includes('fullName'))) {
        const parsedJson = JSON.parse(subject);
        if (parsedJson && typeof parsedJson === 'object') {
          return { isJson: true, data: parsedJson };
        }
      }
    } catch (e) {
      console.warn('Metadata check skipped:', e);
    }

    // 2. Extract text items from PDF pages
    let fullText = '';
    for (let pageNum = 1; pageNum <= pdf.numPages; pageNum++) {
      const page = await pdf.getPage(pageNum);
      const textContent = await page.getTextContent();
      const pageText = textContent.items.map(item => item.str).join(' ');
      fullText += pageText + '\n';
    }

    if (!fullText.trim()) {
      throw new Error('This PDF file contains scanned image data without readable text. Please upload a text-based PDF, DOCX, or TXT file.');
    }

    return { isJson: false, text: fullText };
  }

  throw new Error('Unsupported file format. Please upload a PDF, DOCX, or TXT file.');
}
